/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.ESRepository
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object RepositoriesApi {

  /**
   * you can search for available repositories in the storage service 
   * 
   * Expected answers:
   *   code 200 : Seq[ESRepository] (search results matching criteria)
   */
  def listRepositories(): ApiRequest[Seq[ESRepository]] =
    ApiRequest[Seq[ESRepository]](ApiMethods.GET, "https://virtserver.swaggerhub.com/EVER_TEAM_SOFTWARE/Storage/1.0.0", "/repositories", "application/json")
      .withSuccessResponse[Seq[ESRepository]](200)
      

}

