/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class ESFile (
  id: Option[ESFileId],
  /* The files parent list. Some drives juste manage one parent */
  parents: Option[Seq[ESParent]],
  /* The title of the file */
  name: Option[String],
  /* The size of the file in bytes. */
  fileSize: Option[Long],
  /* true if file is a directory, false otherwise */
  directory: Option[Boolean],
  /* A short description of the file */
  description: Option[String],
  /* The MIME type of the file */
  mimeType: Option[String],
  /* Creation time for this file */
  creationTime: Option[DateTime],
  /* Last time this file was modified by anyone */
  lastModifiedTime: Option[DateTime],
  /* Last time this file was acceded by anyone */
  lastAccessTime: Option[DateTime],
  lastModifiedUser: Option[ESUser],
  owners: Option[Seq[ESUser]],
  permissions: Option[Seq[ESPermission]],
  /* The file's content  MD5 checksum */
  checksum: Option[String]
) extends ApiModel


