/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class ESPermission (
  /* The permission type. Allow or deny */
  `type`: Option[ESPermissionEnums.&#x60;Type&#x60;],
  /* The account type. */
  accountType: Option[ESPermissionEnums.AccountType],
  /* The id (can be its email or user code) of the user or group this permission refers to */
  userId: Option[String],
  /* The domain name of the entity this permission refers to. It is present when the permission type is user, group or domain */
  domain: Option[String],
  roles: Option[ESPermissionEnums.Seq[Roles]]
) extends ApiModel

object ESPermissionEnums {

  type &#x60;Type&#x60; = &#x60;Type&#x60;.Value
  type AccountType = AccountType.Value
  type Seq[Roles] = Seq[Roles].Value
  object &#x60;Type&#x60; extends Enumeration {
    val Allow = Value("allow")
    val Deny = Value("deny")
  }

  object AccountType extends Enumeration {
    val User = Value("user")
    val Group = Value("group")
    val Domain = Value("domain")
    val Anyone = Value("anyone")
  }

  object Seq[Roles] extends Enumeration {
  }

}

