/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class ESRepository (
  id: Option[ESFileId],
  `type`: Option[ESRepositoryEnums.&#x60;Type&#x60;],
  name: Option[String],
  /* can be a reference to json file containing all client secrets */
  rootDirectory: Option[String],
  /* can be a reference to json file containing all client secrets */
  clientSecrets: Option[String]
) extends ApiModel

object ESRepositoryEnums {

  type &#x60;Type&#x60; = &#x60;Type&#x60;.Value
  object &#x60;Type&#x60; extends Enumeration {
    val FS = Value("FS")
    val GOOGLE = Value("GOOGLE")
    val ONEDRIVE = Value("ONEDRIVE")
  }

}

